name: CI  #Workflow name
on: [push, pull_request] # when the workflow is triggered
jobs:
  build:
    runs-on: ubuntu-latest # where to run pulls the image
    steps:    # individual tasks for the job
        - name: ⬇️ Checkout Code   # Uses GitHub's official action to clone the repo so that it can access your code
          uses: actions/checkout@v4

        - name: 🐢 Setup Node   # Installs Node.js using the version defined in your .nvmrc file or your specified version, This ensures consistent Node version across machines.
          uses: actions/setup-node@v4
          with:
            node-version-file: '.nvmrc'

        - name: 🏗️ Install Dependencies   # Installs the project dependencies from package.json
          run: npm install

        - name: 🧪 Test   # Runs your test suite via the custom script test:local defined in your package.json.
          run: npm run test:local

        - name: 📦 Upload Logs    # If any step fails, this will: Upload your test logs or screenshots stored in the logs/ folder. This helps with debugging failed CI runs.
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs
